# Generated by Django 5.0.5 on 2024-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=100)),
                ("eemail", models.EmailField(max_length=254, unique=True)),
                ("econtact", models.BigIntegerField()),
            ],
        ),
    ]
